# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 2

[[main]]
  name = "Notes"
  url = "/notes/"
  weight = 3

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
  
################################
# Notes
################################

# ML

[[machine-learning]]
  name = "ML Fundamentals"
  weight = 20
  identifier = "ml-fundamentals"

[[machine-learning]]
  name = "Model Selection"
  weight = 20
  identifier = "model-selection"

[[machine-learning]]
  name = "Regression"
  weight = 30
  identifier = "regression"

[[machine-learning]]
  name = "Classification"
  weight = 40
  identifier = "classification"

[[machine-learning]]
  name = "Decision Trees"
  weight = 50
  identifier = "decision-tree"

[[machine-learning]]
  name = "Ensemble Learning"
  weight = 60
  identifier = "ensemble-learning"

[[machine-learning]]
  name = "Non-Parametric"
  weight = 60
  identifier = "non-parametric"


# Python 
[[python]]
  name = "Python Basics"
  weight = 10
  identifier = "py-basics"

[[python]]
  name = "Best Practice"
  weight = 20
  identifier = "py-best-practice"


# Rechnerstruktur
[[rechner-struktur]]
  name = "Grundlagen"
  weight = 10
  identifier = "grundlagen"

[[rechner-struktur]]
  name = "Prozessortechniken"
  weight = 20
  identifier = "prozessor-techniken"

[[rechner-struktur]]
  name = "Multiprozessoren"
  weight = 30
  identifier = "multiprozessoren"

[[rechner-struktur]]
  name = "Weitere Rechnerstrukturen"
  weight = 40
  identifier = "weitere-rechnerstrukturen"

[[rechner-struktur]]
  name = "Übung Zusammenfassung"
  weight = 50
  identifier = "uebung-zusammenfassung"

################################
# Courses
################################
[[example]]
  name = "Example Topic"
  weight = 10
  identifier = "example-topic"

[[example]]
  name = "Another Topic"
  weight = 20
  identifier = "another-topic"