# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 2

[[main]]
  name = "AI"
  url = "/ai/"
  weight = 3

[[main]]
  name = "Python"
  url = "/python/"
  weight = 4

[[main]]
  name = "Notes"
  url = "/notes/"
  weight = 5

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
  
################################
# Notes
################################

# ML

[[machine-learning]]
  name = "ML Fundamentals"
  weight = 20
  identifier = "ml-fundamentals"

[[machine-learning]]
  name = "Model Selection"
  weight = 20
  identifier = "model-selection"

[[machine-learning]]
  name = "Regression"
  weight = 30
  identifier = "regression"

[[machine-learning]]
  name = "Classification"
  weight = 40
  identifier = "classification"

[[machine-learning]]
  name = "Decision Trees"
  weight = 50
  identifier = "decision-tree"

[[machine-learning]]
  name = "Ensemble Learning"
  weight = 60
  identifier = "ensemble-learning"

[[machine-learning]]
  name = "Non-Parametric"
  weight = 60
  identifier = "non-parametric"


# Python 
[[python]]
  name = "Python Basics"
  weight = 10
  identifier = "py-basics"

[[python]]
  name = "Best Practice"
  weight = 20
  identifier = "py-best-practice"

[[python]]
  name = "Numpy"
  weight = 30
  identifier = "numpy"

[[python]]
  name = "Pandas"
  weight = 40
  identifier = "pandas"

[[python]]
  name = "Visualization"
  weight = 50
  identifier = "visualization"

# Rechnerstruktur
[[rechner-struktur]]
  name = "Grundlagen"
  weight = 10
  identifier = "grundlagen"

[[rechner-struktur]]
  name = "Prozessortechniken"
  weight = 20
  identifier = "prozessor-techniken"

[[rechner-struktur]]
  name = "Multiprozessoren"
  weight = 30
  identifier = "multiprozessoren"

[[rechner-struktur]]
  name = "Vektorverarbeitung"
  weight = 40
  identifier = "vektor-verarbeitung"

[[rechner-struktur]]
  name = "Übung Zusammenfassung"
  weight = 50
  identifier = "uebung-zusammenfassung"

[[rechner-struktur]]
  name = "Notes von Rechnerorganisation"
  weight = 60
  identifier = "notes-von-ro"

[[rechner-struktur]]
  name = "Alte Klausur Zusammenfassung"
  weight = 70
  identifier = "alte-klausur-zusammenfassung"

# Deep Learning
[[deep-learning]]
  name = "Neural Network Basics"
  weight = 10
  identifier = "nn-basics"

[[deep-learning]]
  name = "Generalization"
  weight = 15
  identifier = "generalization"

[[deep-learning]]
  name = "Efficient Training"
  weight = 20
  identifier = "efficient-training"

[[deep-learning]]
  name = "Unsupervised Learning"
  weight = 30
  identifier = "unsupervised-learning"

[[deep-learning]]
  name = "CNN"
  weight = 40
  identifier = "cnn"

[[deep-learning]]
  name = "Parallelism"
  weight = 50
  identifier = "parallelism"

[[deep-learning]]
  name = "RNN"
  weight = 60
  identifier = "rnn"

[[deep-learning]]
  name = "Encoder Decoder Model"
  weight = 70
  identifier = "encoder-decoder"

[[deep-learning]]
  name = "Reinforcement-learning"
  weight = 80
  identifier = "rl"


# NLP
[[natural-language-processing]]
  name = "Regular Expressions, Text Normalization, and Edit Distance"
  weight = 10
  identifier = "re-tn-ed"

[[natural-language-processing]]
  name = "Language Modeling with N-Grams"
  weight = 20
  identifier = "LM-N-gram"

[[natural-language-processing]]
  name = "Naive Bayes and Sentiment Classification"
  weight = 30
  identifier = "navie-bayes"

[[natural-language-processing]]
  name = "Logistic Regression"
  weight = 40
  identifier = "logistic-reg"

[[natural-language-processing]]
  name = "Vector Semantics and Embeddings"
  weight = 50
  identifier = "vector-semantics-embeddings"

[[natural-language-processing]]
  name = "Neural Nets and Neural Language Models"
  weight = 60
  identifier = "nn-LM"

[[natural-language-processing]]
  name = "Part-of-Speech Tagging"
  weight = 70
  identifier = "POS-tagging"

[[natural-language-processing]]
  name = "Sequence Processing with Recurrent Networks"
  weight = 80
  identifier = "sequence-processing-rnn"

[[natural-language-processing]]
  name = "Encoder-Decoder Models, Attention, and Contextual Embeddings"
  weight = 90
  identifier = "encoder-decoder"

[[natural-language-processing]]
  name = "Lecture Notes"
  weight = 100
  identifier = "lecture-notes"

# pytorch
[[pytorch]]
  name = "Getting Started"
  weight = 10
  identifier = "getting-started"

[[pytorch]]
  name = "Recipes"
  weight = 90
  identifier = "pytorch-recipese"

################################
# Courses
################################
[[example]]
  name = "Example Topic"
  weight = 10
  identifier = "example-topic"

[[example]]
  name = "Another Topic"
  weight = 20
  identifier = "another-topic"