# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 2

[[main]]
  name = "AI"
  url = "/ai/"
  identifier = "ai"
  weight = 3

[[main]]
  name = "Machine Learning"
  url = "/ai/machine-learning/"
  weight = 1
  identifier = "ml"
  parent = "ai"

[[main]]
  name = "Deep Learning"
  url = "/ai/deep-learning/"
  weight = 2
  identifier = "dl"
  parent = "ai"

[[main]]
  name = "Computer Vision"
  url = "/ai/computer-vision/"
  weight = 3
  identifier = "cv"
  parent = "ai"

[[main]]
  name = "Nature Language Processing"
  url = "/ai/natural-language-processing/"
  weight = 4
  identifier = "nlp"
  parent = "ai"

[[main]]
  name = "PyTorch"
  url = "/ai/pytorch/"
  weight = 5
  identifier = "pytorch"
  parent = "ai"

[[main]]
  name = "Programming"
  url = "/programming/"
  weight = 4
  identifier = "programming"

[[main]]
  name = "Python"
  url = "/programming/python/"
  weight = 1
  identifier = "python"
  parent = "programming"

[[main]]
  name = "Software Engineering"
  url = "/programming/software-engineering/"
  weight = 2
  identifier = "software-engineering"
  parent = "programming"

[[main]]
  name = "Docker"
  url = "/programming/docker/"
  weight = 3
  identifier = "docker"
  parent = "programming"

[[main]]
  name = "Linux"
  url = "/programming/linux/"
  weight = 4
  identifier = "linux"
  parent = "programming"

[[main]]
  name = "Notes"
  url = "/notes/"
  weight = 5

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
  

################################################################
# AI                                                           #
################################################################


################################
# ML                           #
################################
[[machine-learning]]
  name = "ML Fundamentals"
  weight = 10
  identifier = "ml-fundamentals"

[[machine-learning]]
  name = "Model Selection"
  weight = 20
  identifier = "model-selection"

[[machine-learning]]
  name = "Regression"
  weight = 30
  identifier = "regression"

[[machine-learning]]
  name = "Classification"
  weight = 40
  identifier = "classification"

[[machine-learning]]
  name = "Decision Trees"
  weight = 50
  identifier = "decision-tree"

[[machine-learning]]
  name = "Ensemble Learning"
  weight = 60
  identifier = "ensemble-learning"

[[machine-learning]]
  name = "Non-Parametric"
  weight = 70
  identifier = "non-parametric"

[[machine-learning]]
  name = "Unsupervised Learning"
  weight = 80
  identifier = "unsupervised"



################################
# DL                           #
################################
[[deep-learning]]
  name = "Neural Network Basics"
  weight = 10
  identifier = "nn-basics"

[[deep-learning]]
  name = "Generalization"
  weight = 15
  identifier = "generalization"

[[deep-learning]]
  name = "Efficient Training"
  weight = 20
  identifier = "efficient-training"

[[deep-learning]]
  name = "Unsupervised Learning"
  weight = 30
  identifier = "unsupervised-learning"

[[deep-learning]]
  name = "CNN"
  weight = 40
  identifier = "cnn"

[[deep-learning]]
  name = "Parallelism"
  weight = 50
  identifier = "parallelism"

[[deep-learning]]
  name = "RNN"
  weight = 60
  identifier = "rnn"

[[deep-learning]]
  name = "Encoder Decoder Model"
  weight = 70
  identifier = "encoder-decoder"

[[deep-learning]]
  name = "Reinforcement-learning"
  weight = 80
  identifier = "rl"


################################
# NLP                          #
################################
[[natural-language-processing]]
  name = "Regular Expressions, Text Normalization, and Edit Distance"
  weight = 10
  identifier = "re-tn-ed"

[[natural-language-processing]]
  name = "Language Modeling with N-Grams"
  weight = 20
  identifier = "LM-N-gram"

[[natural-language-processing]]
  name = "Naive Bayes and Sentiment Classification"
  weight = 30
  identifier = "navie-bayes"

[[natural-language-processing]]
  name = "Logistic Regression"
  weight = 40
  identifier = "logistic-reg"

[[natural-language-processing]]
  name = "Vector Semantics and Embeddings"
  weight = 50
  identifier = "vector-semantics-embeddings"

[[natural-language-processing]]
  name = "Neural Nets and Neural Language Models"
  weight = 60
  identifier = "nn-LM"

[[natural-language-processing]]
  name = "Part-of-Speech Tagging"
  weight = 70
  identifier = "POS-tagging"

[[natural-language-processing]]
  name = "Sequence Processing with Recurrent Networks"
  weight = 80
  identifier = "sequence-processing-rnn"

[[natural-language-processing]]
  name = "Encoder-Decoder Models, Attention, and Contextual Embeddings"
  weight = 90
  identifier = "encoder-decoder"

[[natural-language-processing]]
  name = "Information Extraction"
  weight = 180
  identifier = "info-extraction"

[[natural-language-processing]]
  name = "Lecture Notes"
  weight = 200
  identifier = "lecture-notes"


################################
# PyTorch                      #
################################
[[pytorch]]
  name = "Getting Started"
  weight = 10
  identifier = "getting-started"

[[pytorch]]
  name = "Deep Learning with PyTorch"
  weight = 20
  identifier = "dl-with-pytorch"

[[pytorch]]
  name = "fastai"
  weight = 40
  identifier = "fastai"

[[pytorch]]
  name = "Object Detection"
  weight = 50
  identifier = "object-detection"

[[pytorch]]
  name = "Recipes"
  weight = 90
  identifier = "pytorch-recipes"

[[pytorch]]
  name = "Training"
  weight = 100
  identifier = "training"

################################
# CV                           #
################################
[[computer-vision]]
  name = "Lecture"
  weight = 10
  identifier = "cv-lecture"

[[computer-vision]]
  name = "Object detection"
  weight = 100
  identifier = "object-detection"

################################################################
# Programming                                                  #
################################################################

################################
# Python                       #
################################
[[python]]
  name = "Python Basics"
  weight = 10
  identifier = "py-basics"

[[python]]
  name = "Best Practice"
  weight = 20
  identifier = "py-best-practice"

[[python]]
  name = "Numpy"
  weight = 30
  identifier = "numpy"

[[python]]
  name = "Pandas"
  weight = 40
  identifier = "pandas"

[[python]]
  name = "Visualization"
  weight = 50
  identifier = "visualization"

[[python]]
  name = "IPython"
  weight = 60
  identifier = "ipython"


################################
# Software Engineering         #
################################
[[software-engineering]]
  name = "Design Patterns"
  weight = 10
  identifier = "design-patterns"

[[software-engineering]]
  name = "High Quality Systems: Implementation"
  weight = 20
  identifier = "implementing-high-quality-systems"

[[software-engineering]]
  name = "High Quality Systems: Design"
  weight = 30
  identifier = "designing-high-quality-systems"

################################
# Docker                       #
################################
[[docker]]
  name = "Getting Started"
  weight = 10
  identifier = "docker-getting-started"

[[docker]]
  name = "Best Practices"
  weight = 20
  identifier = "docker-best-practices"

[[docker]]
  name = "Docker Recipes"
  weight = 30
  identifier = "docker-recipes"


################################
# Linux                        #
################################
[[linux]]
  name = "Getting Started"
  weight = 10
  identifier = "linux-getting-started"

[[linux]]
  name = "Linux Learn"
  weight = 10
  identifier = "linux-learn"

[[linux]]
  name = "Linux Recipes"
  weight = 10
  identifier = "linux-recipes"



################################################################
# Notes                                                        #
################################################################

# gestaltungsgrundsaetze-fuer-interaktive-echtzeitsysteme
[[gestaltungsgrundsaetze-fuer-interaktive-echtzeitsysteme]]
  name = "Vorlesung"
  weight = 10
  identifier = "vorlesung"


# Rechnerstruktur
[[rechner-struktur]]
  name = "Grundlagen"
  weight = 10
  identifier = "grundlagen"

[[rechner-struktur]]
  name = "Prozessortechniken"
  weight = 20
  identifier = "prozessor-techniken"

[[rechner-struktur]]
  name = "Multiprozessoren"
  weight = 30
  identifier = "multiprozessoren"

[[rechner-struktur]]
  name = "Vektorverarbeitung"
  weight = 40
  identifier = "vektor-verarbeitung"

[[rechner-struktur]]
  name = "Übung Zusammenfassung"
  weight = 50
  identifier = "uebung-zusammenfassung"

[[rechner-struktur]]
  name = "Notes von Rechnerorganisation"
  weight = 60
  identifier = "notes-von-ro"

[[rechner-struktur]]
  name = "Alte Klausur Zusammenfassung"
  weight = 70
  identifier = "alte-klausur-zusammenfassung"


################################
# Courses                       
################################
[[example]]
  name = "Example Topic"
  weight = 10
  identifier = "example-topic"

[[example]]
  name = "Another Topic"
  weight = 20
  identifier = "another-topic"

  
